export const VIDEOS = {
  instagram: "https://instagram.com/uphiago",
  yt: [
    {
      id: "yt1",
      title: "Self-hosted CI/CD with n8n - replacing $$$ SaaS",
      meta: "8.2k views · 3 days ago",
      duration: "22:14",
      thumb: "https://picsum.photos/seed/n8n-cicd-2026/800/450",
      desc: "Walk-through of the n8n-based CI/CD I run for my own projects. From webhook to deploy, no GitHub Actions minutes burned.",
      tags: ["#n8n", "#cicd", "#selfhosted"],
    },
    {
      id: "yt2",
      title: "MCP architectures & tool-calling agents",
      meta: "5.4k views · 2 weeks ago",
      duration: "17:42",
      thumb: "https://picsum.photos/seed/mcp-agents-2026/800/450",
      desc: "Deep-dive on Model Context Protocol - what it solves, how to write an MCP server, and patterns for tool-calling LLM agents.",
      tags: ["#mcp", "#ai", "#agents"],
    },
    {
      id: "yt3",
      title: "GitOps drift checks that don't wake you up",
      meta: "3.1k views · 1 month ago",
      duration: "14:08",
      thumb: "https://picsum.photos/seed/gitops-drift-2026/800/450",
      desc: "A practical drift detection setup for Kubernetes clusters, with alerts that only fire when a human needs to act.",
      tags: ["#gitops", "#k8s", "#drift"],
    },
    {
      id: "yt4",
      title: "Homelab monitoring stack from scratch",
      meta: "2.8k views · 2 months ago",
      duration: "19:36",
      thumb: "https://picsum.photos/seed/homelab-observability-2026/800/450",
      desc: "Prometheus, Grafana, logs, uptime checks, and a simple incident dashboard for a small self-hosted environment.",
      tags: ["#monitoring", "#grafana", "#homelab"],
    },
    {
      id: "yt5",
      title: "Deploy preview environments without SaaS CI",
      meta: "1.9k views · 3 months ago",
      duration: "16:22",
      thumb: "https://picsum.photos/seed/preview-envs-2026/800/450",
      desc: "How I spin up isolated preview stacks with Docker, Traefik, and a small n8n workflow.",
      tags: ["#docker", "#traefik", "#preview"],
    },
    {
      id: "yt6",
      title: "MCP server for internal runbooks",
      meta: "1.4k views · 4 months ago",
      duration: "12:40",
      thumb: "https://picsum.photos/seed/mcp-runbooks-2026/800/450",
      desc: "A compact MCP server that exposes incident runbooks, service owners, and safe operational actions.",
      tags: ["#mcp", "#runbooks", "#ops"],
    },
  ],
  shorts: [
    {
      id: "s1",
      title: "n8n flow in 40 sec",
      meta: "31k · trending",
      duration: "0:42",
      thumb: "https://picsum.photos/seed/n8n-tip-2026/400/720",
      tags: ["#n8n", "#automation"],
      desc: "Drop-in n8n workflow that watches a Slack channel for keywords and triages incidents. Forty seconds, zero fluff.",
      url: "https://instagram.com/p/n8n-tip",
    },
    {
      id: "s2",
      title: "Terraform tip · GitOps",
      meta: "22k · last week",
      duration: "0:58",
      thumb: "https://picsum.photos/seed/tf-tip-2026/400/720",
      tags: ["#terraform", "#gitops"],
      desc: "Terraform module pattern I use across every multi-cloud project. Drift-resistant, GitOps-friendly, painfully simple.",
      url: "https://instagram.com/p/tf-tip",
    },
    {
      id: "s3",
      title: "Docker cleanup alias",
      meta: "18k · quick tip",
      duration: "0:31",
      thumb: "https://picsum.photos/seed/docker-cleanup-2026/400/720",
      tags: ["#docker", "#ops"],
      desc: "The cleanup alias I use before every demo box gets out of hand.",
      url: "https://instagram.com/p/docker-cleanup",
    },
    {
      id: "s4",
      title: "One-line k8s context check",
      meta: "14k · saved",
      duration: "0:27",
      thumb: "https://picsum.photos/seed/k8s-context-2026/400/720",
      tags: ["#k8s", "#shell"],
      desc: "Tiny shell prompt check that prevents deploying to the wrong Kubernetes context.",
      url: "https://instagram.com/p/k8s-context",
    },
    {
      id: "s5",
      title: "n8n retry pattern",
      meta: "11k · automation",
      duration: "0:45",
      thumb: "https://picsum.photos/seed/n8n-retry-2026/400/720",
      tags: ["#n8n", "#retries"],
      desc: "A compact retry pattern for n8n workflows that call flaky external APIs.",
      url: "https://instagram.com/p/n8n-retry",
    },
    {
      id: "s6",
      title: "LogQL in one line",
      meta: "9k · logs",
      duration: "0:36",
      thumb: "https://picsum.photos/seed/logql-one-line-2026/400/720",
      tags: ["#logs", "#loki"],
      desc: "The LogQL query I keep around for fast incident triage.",
      url: "https://instagram.com/p/logql-one-line",
    },
    {
      id: "s7",
      title: "Safe deploy check",
      meta: "8k · deploys",
      duration: "0:29",
      thumb: "https://picsum.photos/seed/safe-deploy-check-2026/400/720",
      tags: ["#deploy", "#ci"],
      desc: "A tiny preflight script that catches the boring deploy mistakes.",
      url: "https://instagram.com/p/safe-deploy",
    },
    {
      id: "s8",
      title: "Webhook sanity test",
      meta: "7k · n8n",
      duration: "0:33",
      thumb: "https://picsum.photos/seed/webhook-sanity-2026/400/720",
      tags: ["#webhook", "#n8n"],
      desc: "Quick webhook validation pattern before a workflow reaches production.",
      url: "https://instagram.com/p/webhook-sanity",
    },
  ],
};

export const ARTICLES = [
  {
    id: "01",
    title: "Self-hosted CI/CD with n8n - replacing $$$ SaaS",
    meta: "9 min · set 2026",
    tags: ["n8n", "self-hosted", "ci/cd"],
    body: [
      { t: "h", v: "Why self-host CI/CD" },
      { t: "p", v: "After a year paying four figures a month for hosted CI, I rebuilt the same flows on n8n + a single VPS. Costs dropped 92% and reliability went up." },
      { t: "p", v: "This post walks through the architecture, the trade-offs, and the n8n nodes I lean on the most." },
      { t: "h", v: "The architecture" },
      { t: "code", v: "github-webhook → n8n → docker-build → registry → argo-deploy" },
      { t: "p", v: "n8n handles the orchestration. GitHub Actions still runs unit tests, but everything past that lives on our side." },
      { t: "h", v: "What I learned" },
      { t: "ul", v: ["self-hosting isn't scary - it's mostly observability","most SaaS CI features are just sugar","you can rebuild any of them in a weekend"] },
      { t: "p", v: "The repo is open source. PRs welcome." },
    ],
  },
  {
    id: "02",
    title: "MCP architectures & tool-calling agents",
    meta: "11 min · ago 2026",
    tags: ["ai", "mcp", "agents"],
    body: [
      { t: "h", v: "What MCP solves" },
      { t: "p", v: "Model Context Protocol gives LLMs a structured way to call tools - APIs, file systems, databases - without prompt-engineering the schema every time." },
      { t: "h", v: "A minimal MCP server" },
      { t: "code", v: "// tools.ts\nexport const tools = {\n  query_db: { schema, handler },\n  fetch_logs: { schema, handler },\n};" },
      { t: "p", v: "From there, any LLM client that speaks MCP can discover and invoke your tools - Claude Desktop, custom agents, n8n nodes." },
      { t: "h", v: "Patterns that work" },
      { t: "ul", v: ["narrow tools beat wide tools","return structured errors","cache aggressively, the LLM will retry"] },
    ],
  },
  {
    id: "03",
    title: "Multi-cloud networking - AWS, GCP & Azure",
    meta: "8 min · jul 2026",
    tags: ["cloud", "networking", "terraform"],
    body: [
      { t: "h", v: "The real cost of multi-cloud" },
      { t: "p", v: "It's not the compute - it's the network. Egress fees, peering, DNS, latency. Plan the network first, services second." },
      { t: "h", v: "VPN mesh vs interconnect" },
      { t: "p", v: "For < 1 Gbps steady traffic, a Tailscale or Wireguard mesh is fine. Past that, dedicated interconnect pays for itself in egress savings inside the first quarter." },
      { t: "h", v: "Terraform patterns" },
      { t: "code", v: "module \"network\" {\n  source = \"./modules/multi-cloud-net\"\n  providers = { aws, gcp, azurerm }\n}" },
      { t: "p", v: "One module, three providers, shared variables. The repo has the full source." },
    ],
  },
  {
    id: "04",
    title: "13 years in infrastructure - what I'd do differently",
    meta: "6 min · jun 2026",
    tags: ["retrospective", "career"],
    body: [
      { t: "p", v: "Half-baked retrospective from a Sunday evening. Not advice, just notes." },
      { t: "h", v: "Three things I'd start sooner" },
      { t: "ul", v: ["self-host earlier - SaaS is a tax on inertia","write more, ship more public code","say no to one-off heroics"] },
      { t: "h", v: "Three things I'm glad I did" },
      { t: "ul", v: ["went deep on networking before going wide on cloud","worked across three industries (gov, esports, fintech)","kept a personal lab running for 10 years"] },
      { t: "p", v: "The pattern: every long-term win came from controlling my own stack." },
    ],
  },
  {
    id: "05",
    title: "Preview environments on a single VPS",
    meta: "7 min · mai 2026",
    tags: ["docker", "traefik", "preview"],
    body: [
      { t: "h", v: "Small preview stacks" },
      { t: "p", v: "A cheap VPS can run useful preview environments when the workflow is strict about cleanup, naming, and routing." },
      { t: "code", v: "branch -> image -> compose project -> traefik route" },
    ],
  },
  {
    id: "06",
    title: "Runbooks that agents can actually use",
    meta: "10 min · abr 2026",
    tags: ["mcp", "incident", "ops"],
    body: [
      { t: "h", v: "Runbooks as tools" },
      { t: "p", v: "The useful pattern is narrow MCP tools around verified runbook actions, not a broad shell with production access." },
      { t: "ul", v: ["return structured status", "keep actions reversible", "log every tool call"] },
    ],
  },
];
